### ISSUE TITLE
ERROR in GUI when i load a geometry

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#455] opened 2017-12-08 16:50 UTC
When i load a geometry in the GUI, i have the following error : 
![image](https://user-images.githubusercontent.com/19569215/33775916-247d152a-dc40-11e7-9ecf-ff0b513b2d51.png)

**Comment by SteveDoyle2** [comment] 2017-12-08 17:07
I've seen that error, but haven't been able to reproduce it.  Can you list
the steps?

**Comment by PabloBeranger** [comment] 2017-12-08 18:01
1)  I open the PowerShell Windows
2) I write pyNastranGUI 
          pyNastranGUI is in the python script folder ( for me D:\Python27\Scripts)
3) The pyNastran GUI is openning
4) I choose : File - Load Geometry
       
![image](https://user-images.githubusercontent.com/19569215/33778553-7fe3a100-dc49-11e7-9410-ca19e78d5cbc.png)

5) The Windows "Choose a Geometry File to Load " will appear
   
![image](https://user-images.githubusercontent.com/19569215/33778680-0bb03432-dc4a-11e7-9a5f-4e88f7b9a25c.png)

6) I select the file and i click the open button

7) The ERROR message appear

**Comment by SteveDoyle2** [comment] 2017-12-08 18:11
I tested that process today and have no issues.  Can you update to the latest version and test again?

**Comment by PabloBeranger** [comment] 2017-12-08 18:55
You can see in the first message, in the powershell windows that is the last.
pyNastran is updated from your Github Depot and i link the last version today.

**Comment by SteveDoyle2** [comment] 2017-12-08 19:12
"v1.1.0+dev.no.checksum.error" means that the git checksum could not be determined.  Thus, you either downloaded from source or used setup.py install (vs. setup.py develop from a git checkout).  In either case, it's possible that you're out of date, even though you redownloaded it today.

Can you try to load the models/solid_bending geometry?

**Comment by PabloBeranger** [comment] 2017-12-09 07:55
I try to load the models/solid_bending geometry and i have the same error.

My pyNastran Installation is : 
   1) I create a directory : D:\Github_Depots\PyNastran
   2) I downloaded the last pyNastran version in zip file
   3) I copied the pyNastran_master_XXXXXXXX.zip in this directory
   4) I installed pyNastran with the command : python setup.py develop

what are your recommendations to be certain to have the latest version ?

**Comment by SteveDoyle2** [comment] 2017-12-09 08:44
I suspect you have an new version installed on top of an older version.  However, the older version is taking priority.

I would clear out the references to pyNastran in `C:\Python27\Lib\site-packages` (i.e., delete the folders that have pyNastran in them).  Then I would open `easy_install.pth` and `setuptools.pth`  that are in that same folder and remove any references to pyNastran.  While you're at it, I'd remove duplicate versions of numpy, scipy, etc. 

Then I would reinstall it.

**Comment by SteveDoyle2** [comment] 2017-12-09 09:15
Oh, ok...that makes more sense.  I'll have to take a look later though.

The easy solution is just to update to PyQt5.

**Comment by SteveDoyle2** [comment] 2017-12-09 09:18
You can also just call:

    pyNastranGUI model.bdf
    pyNastranGUI model.dat -f nastran
    pyNastranGUI model.bdf model.op2

etc.

**Comment by PabloBeranger** [comment] 2017-12-09 09:21
I will see if I can install PyQT5
Thanks.

**Comment by PabloBeranger** [comment] 2017-12-09 16:19
There is no version of PyQt5 for python 2.7.
I have to compile the PyQt5 source for python 2.7 and compilation it's not my strong point ....

**Comment by SteveDoyle2** [comment] 2017-12-09 16:45
I suggest using Anaconda Python then.  They have their own whl server and
it also comes with a C++ compiler.

Anaconda is so much easier for managing packages and it'll speed up your
numpy by ~4x on Windows because it's compiled with the Intel MKL libraries.

**Comment by SteveDoyle2** [comment] 2017-12-11 01:44
This is fixed now.

**Closed by SteveDoyle2** 2017-12-11 01:44 UTC
