### ISSUE TITLE
MONPNT3 (ref #352 issue)

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#358] opened 2017-01-09 14:32 UTC
The reading of the Monitor Point 3 (data) is perfect.

The problem is that the monitor point 3 results are stored in `op2.monitor3.data` without a reference to the ID (in the MONTPNT3) of the monitor point.

**Comment by SteveDoyle2** [comment] 2017-01-10 02:35
Can you make an example with 2?  Also can you make sure the coordinate
system and xyz values are different and greater than 3?  The monpnt3 header
is in a different table than the data just like the monpnt1.

On Mon, Jan 9, 2017, 8:32 AM alby3z <notifications@github.com> wrote:

The reading of the Monitor Point 3 (data) is perfect.

The problem is that the monitor point 3 results are stored in
op2.monitor3.data without a reference to the ID (in the MONTPNT3) of the
monitor point.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SteveDoyle2/pyNastran/issues/358>, or mute the thread

**Comment by alby3z** [comment] 2017-01-11 13:44
Attached you find the case with 2 different monitor points.

[TEST_2_MONPNT3_request.zip](https://github.com/SteveDoyle2/pyNastran/files/698996/TEST_2_MONPNT3_request.zip)

Sorry but I didn't catch what do you mean with:

> Also can you make sure the coordinate
> system and xyz values are different and greater than 3?


Where do I find the MONPNT3 table containing the header? I am interested in associate the n-th monitor points with the relative output data, in a similar manner as I have access to the stress on a cbar through its element ID.

**Comment by alby3z** [comment] 2017-01-30 08:39
Do you have any update with regard to the test case above?

How do I reference the particular MONPNT3 (M2_B and M3_B in the example) with the data stored in the op2.monitor3.data?

**Comment by SteveDoyle2** [comment] 2017-02-03 04:46
From what I've seen, the names aren't there.  I also saw that it looked like the definition was spelled out more clearly, which made me think that it might be in one of the subtables.  I've haven't had time to verify that yet, but I was pretty sure I parsed everything.  It's possible it's just listed by index, rather than name.

I do need to close this out though.

**Comment by SteveDoyle2** [comment] 2017-03-27 19:31
The data is not stored in the OP2 for the MONPNT3.  You must use the BDF to get that information.

**Closed by SteveDoyle2** 2017-03-27 19:31 UTC

**Comment by alby3z** [comment] 2017-03-27 20:27
Where did you get this information? Thanks a lot!

**Comment by SteveDoyle2** [comment] 2017-03-29 06:53
I can't find the data in the file.
