### ISSUE TITLE
pyNastran no longer compatible with Python 3.6 due to cpylog dependency

### ISSUE THREAD

**Issue by jdeaton** [SteveDoyle2/pyNastran#586] opened 2020-01-16 22:04 UTC
Steve, you probably are already aware, but pyNastran is no longer compatible with Python 3.6 due to some of the recent changes you made in `cpylog` that moved its requirement to Python 3.7. I thought I would give you a heads up in case you wanted to maintain backwards compatibility.

CI testing on our MAST project that was using Python 3.6 on Linux hit errors, which we quickly traced to those changes. Upgrading to the build worker to Python 3.7 fixed it.

**Comment by SteveDoyle2** [comment] 2020-01-17 00:34
I’m aware, but it’s not due to a change in cpylog.  It’s been required in the master of pyNastran for about 6 months.  Python 3.6 is source only releases now and to do annotations right, you need 3.7.

Python 3.6 works with pyNastran 1.2.

**Comment by SteveDoyle2** [comment] 2020-01-17 00:54
Maybe the solution is to do a 1.2.2 release?

**Comment by SteveDoyle2** [comment] 2020-01-17 00:55
I'm thinking of doing a 1.3 release, but dependencies are not always compatible for future versions and they kind of get forgotten.

**Comment by SteveDoyle2** [comment] 2020-01-19 22:41
I've removed cpylog 1.3.0 from pypi since it was bugged and said it incorrectly supported Python 2.7 and 3.6.  That's not good practice (see when pip did it), but cpylog is not pip.

I'm also working on a fairly large 1.2.2 release with what's intended to be most of the bug fixes from 1.3 of which there are many.  It doesn't include new features like new BDF cards, OP2 writing, modern pandas support, or improved GUI support (loading custom results with blank entries, more results).  It's getting close.  It will be the last 2.7/3.6 release barring some regression.

**Comment by SteveDoyle2** [comment] 2020-02-21 19:29
closing

**Closed by SteveDoyle2** 2020-02-21 19:29 UTC
