### ISSUE TITLE
read_op2_geom skips PSHELL

### ISSUE THREAD

**Issue by AlejandroStewart** [SteveDoyle2/pyNastran#605] opened 2020-05-27 23:00 UTC
Hello Steve, hope you are doing well.

I am having some hiccups here trying to read the geometry from an op2. PSHELLs do not appear on the model.
Pynastran version is 1.3.2
The code is as follows:
```
import os
from pyNastran.op2.op2 import OP2
from pyNastran.op2.op2_geom import read_op2_geom
import pyNastran
print(pyNastran.__version__)
folder='G:\\WORK_ALEJANDRO\\'
op2_files=[i for i in os.listdir(folder) if i.endswith('op2')]

for op2_file in op2_files:
    this_op2=OP2()
    this_op2.read_op2(os.path.join(folder,op2_file),skip_undefined_matrices=True)
    this_model=read_op2_geom(op2_file)
    print(this_op2.get_op2_stats())
```

And apparently Pynastran  sees some PSHELLs:
 (output extract)
DEBUG:   op2_reader.py:1735           table_name = b'GPDT'
DEBUG:   op2_scalar.py:1713             table_name=b'EPT'
DEBUG:   op2_common.py:589              found keys=( 1402,  14,  37) name=PBUSH  - b'EPT'
DEBUG:   op2_common.py:589              found keys=( 2706,  27, 287) name=PCOMP  - b'EPT'
DEBUG:   op2_common.py:589              **_found keys=( 2302,  23, 283) name=PSHELL - b'EPT'_**
DEBUG:   op2_scalar.py:1713             table_name=b'MPT'
DEBUG:   op2_common.py:589              found keys=(  203,   2,  78) name=MAT2   - b'MPT'
DEBUG:   op2_common.py:589              found keys=(  103,   1,  77) name=MAT1   - b'MPT'
DEBUG:   op2_common.py:589              found keys=( 2503,  25, 288) name=MAT8   - b'MPT'
DEBUG:   op2_scalar.py:1713             table_name=b'GEOM2'
DEBUG:   op2_common.py:589              found keys=( 2608,  26,  60) name=CBUSH  - b'GEOM2'
DEBUG:   op2_common.py:589              found keys=( 2958,  51, 177) name=CQUAD4 - b'GEOM2'
DEBUG:   op2_common.py:589              found keys=( 5959,  59, 282) name=CTRIA3 - b'GEOM2'
DEBUG:   op2_scalar.py:1713             table_name=b'GEOM3'
DEBUG:   op2_common.py:589              found keys=( 4201,  42,  18) name=FORCE  - b'GEOM3'
DEBUG:   op2_common.py:589              found keys=( 4551,  61,  84) name=LOAD   - b'GEOM3'
DEBUG:   op2_scalar.py:1713             table_name=b'GEOM4'
DEBUG:   op2_common.py:589              found keys=( 6901,  69, 295) name=RBE2   - b'GEOM4'
DEBUG:   op2_common.py:589              found keys=( 5501,  55,  16) name=SPC    - b'GEOM4'
DEBUG:   op2_scalar.py:1713             table_name=b'GEOM1'
DEBUG:   op2_common.py:589              found keys=( 2001,  20,   9) name=CORD2C - b'GEOM1'
DEBUG:   op2_common.py:589              found keys=( 2101,  21,   8) name=CORD2R - b'GEOM1'
DEBUG:   op2_common.py:589              found keys=( 4501,  45,   1) name=GRID   - b'GEOM1'

The following picture compares the f06 summary and the Pynastran model one:

![image](https://user-images.githubusercontent.com/14002967/83078652-56be7c80-a07a-11ea-8384-c31387944674.png)

I apologize I cannot share the model

I´ll see if I can relicate with a toy model

**Comment by SteveDoyle2** [comment] 2020-05-27 23:09
Hey there!

I suspect you have either
 - PSHELLs with property ids greater than 1e8 (those are stored in the
aptly named big_properties variable)
 - PSHELLs with negative property ids or negative material ids
 - a PCOMP and PSHELL have the property id

Nastran can be weird and I don't know what much of that means.

**Comment by AlejandroStewart** [comment] 2020-05-27 23:30
My PSHELL are not that interesting:
```
PSHELL  457011  10000   .0135   10000           10000
PSHELL  457012  10000   .04     10000           10000
PSHELL  457013  10000   .0675   10000           10000
PSHELL  457014  10000   .027    10000           10000
```

 as expected, if I run read_op2_geom with xref set to True, I get a ton of messages as:
```
KeyError: 'pid=457011 not found, which is required by CQUAD4 eid=5000096.  Allowed Pids=dict_keys([450051, 490001, 490002, 490003, 490007, 490008, 490102, 490103, 490112, 490122, 490123, 490132, 490203, 490205, 590002, 590012, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 116, 117, 118, 119, 120, 350001, 350002, 350003, 350004, 350005, 350006, 350007, 360001, 360002, 360003, 360004, 360005, 360006, 360007, 360008])'
card=CQUAD4   5000096  457011 5001481 5001348 5001347 5001464
```

**Comment by SteveDoyle2** [comment] 2020-05-27 23:36
Yeah without an example, I'm guessing.  The PSHELL is identified, so unless
you have something weird, it should be there.

The PSHELL reader is in
pyNastran.op2.tables.geom.ept

If you go down to the _read_pshell method, you can add a few prints to see
what's going on.

**Comment by AlejandroStewart** [comment] 2020-05-28 12:57
I think I have found it.
The highlighted continue statement was preventing any pshell from being written into the model, both big pshell from pcomp and "normal" pshell.

![image](https://user-images.githubusercontent.com/14002967/83144023-1818d880-a0f3-11ea-8c93-ced37949c5c3.png)
I have comented it and now it works as I expected


attached you will find a toy problem for testing
[missing_pshell_op2_pynastran.zip](https://github.com/SteveDoyle2/pyNastran/files/4695630/missing_pshell_op2_pynastran.zip)

**Comment by SteveDoyle2** [comment] 2020-05-28 13:08
It should only prevent PSHELLs with the same property from being created.
It can’t hit normally and is caused by having overlapping properties in
your superelements.  There is no super element flag, so it gets thrown out.

**Comment by AlejandroStewart** [comment] 2020-05-28 13:25
I think the probleam has also to do with the n value not incremented in line 1788 when the first pshell is for a pcomp, and thus the same property is read over and over, as edata is not changed.

**Comment by SteveDoyle2** [comment] 2020-05-28 14:31
Oh yeah...that is is definitely not good.

I'm surprised that doesn't crash.  At the end of the function, n=len(data)
or it should be...

**Comment by SteveDoyle2** [comment] 2020-06-09 04:53
Oh I fixed that bug a week or so ago, so closing it.  I found many bugs because of it.  Thanks again!

**Closed by SteveDoyle2** 2020-06-09 04:53 UTC

**Comment by AlejandroStewart** [comment] 2020-06-10 23:55
I noticed, thanks!!
 I think I have a new one in the oven, need time to check before I put it here. I just want you to have some entertainment!
